#!/bin/bash
# For development purposes, set BASEDIR to the full path of the kustom
# directory, e.g.  BASEDIR=/home/peterj/kustom go test
if [ "${BASEDIR}" != "" ]
then

  source ${BASEDIR}/plugin/fca.autodata.net/v1/parse-yaml.sh
  source ${BASEDIR}/plugin/fca.autodata.net/v1/thycotic.sh
else
  source $(dirname $0)/../parse-yaml.sh
  source $(dirname $0)/../thycotic.sh
fi

create_variables $1

if [ "${username_key}" = "" ]
then
  username_key=${username}
fi
if [ "${password_key}" = "" ]
then
  password_key=${password}
fi
if [ "${resource_key}" = "" ]
then
  resource_key=${resource}
fi

# need to handle for trailing backslash
raw_username=$(get_secret "${secret}" username password | tr -d '"')
THYCOTIC_USERNAME="${raw_username//\\/\\\\}"
THYCOTIC_PASSWORD=$(get_secret ${secret} password password | tr -d '"')
THYCOTIC_RESOURCE=$(get_secret ${secret} resource password | tr -d '"')

if [ "" == "${host}" ]; then
  host=${THYCOTIC_RESOURCE}
fi

CSI_VSPHERE_CONF=$(cat << EOF
[VirtualCenter "$(echo ${host} | tr -d '"')"]
insecure-flag = "$(echo ${insecure_flag} | tr -d '"')"
user = "${THYCOTIC_USERNAME}"
password = "${THYCOTIC_PASSWORD}"
datacenters = "$(echo ${datacenters} | tr -d '"')"
EOF
)

if [ "" != "${port}" ]; then
  CSI_VSPHERE_CONF=$( cat << EOF
${CSI_VSPHERE_CONF}
port = "$(echo ${port} | tr -d '"')"
EOF
)
fi

if [ "" != "${cluster_id}" ] || [ "" != "${cluster_distribution}" ]; then
  GLOBAL_SECTION=$( cat << EOF
[Global]
EOF
)
  if [ "" != "${cluster_id}" ] || [ "" != "${cluster_distribution}" ]; then
    GLOBAL_SECTION=$( cat << EOF
${GLOBAL_SECTION}
cluster-id = "$(echo ${cluster_id} | tr -d '"')"
EOF
)
  fi

  if [ "" != "${cluster_distribution}" ]; then
    GLOBAL_SECTION=$( cat << EOF
${GLOBAL_SECTION}
cluster-distribution = "$(echo ${cluster_distribution} | tr -d '"')"
EOF
)
  fi

  CSI_VSPHERE_CONF=$( cat << EOF
${GLOBAL_SECTION}

${CSI_VSPHERE_CONF}
EOF
)
fi

CSI_VSPHERE_CONF=$(echo "${CSI_VSPHERE_CONF}" | openssl base64 -A)

echo "apiVersion: v1"
echo "kind: Secret"
echo "metadata:"
echo "  name: ${metadata_name}"
if [ "" != "${metadata_namespace}" ]; then
  echo "  namespace: ${metadata_namespace}"
fi

echo "data:"
if [ "" != "${username_key}" ] || [ "" != "${password_key}" ]; then
  echo "data:"
fi
if [ "" != "${username_key}" ]; then
  echo "  ${host}.${username_key}: $(echo "${THYCOTIC_USERNAME}" | openssl base64 -A)"
fi
if [ "" != "${password_key}" ]; then
  echo "  ${host}.${password_key}: $(echo "${THYCOTIC_PASSWORD}" | openssl base64 -A)"
fi

echo "  csi-vsphere.conf: >-"
echo "    ${CSI_VSPHERE_CONF}"

