---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: messaging
      app.kubernetes.io/version: 3.8.3-management-alpine
  endpoints:
    - port: metrics