kind: Secret
apiVersion: v1
metadata:
  name: logging-logwriter-role
  namespace: logging
stringData:
  roles.yml: |-
    log_writer:
      cluster: [ 'manage_index_templates', 'monitor', 'manage_ilm', 'read_ilm' ]
      indices:
      - names: [ 'access', 'application', 'errors', 'dead-letter', 'logging-*', 'logstash-*', 'filebeat-*', 'k8s-*', 'photon-*' ]
        privileges: [ 'write', 'create', 'create_index', 'manage', 'manage_ilm', 'view_index_metadata' ]


#Available index privileges [none=[none],create_doc=[create_doc],create=[create],auto_configure=[auto_configure],create_index=[create_index],delete=[delete],delete_index=[delete_index],index=[index],maintenance=[maintenance],manage_follow_index=[manage_follow_index],manage_ilm=[manage_ilm],manage_leader_index=[manage_leader_index],monitor=[monitor],view_index_metadata=[view_index_metadata],manage=[manage],read=[read],read_cross_cluster=[read_cross_cluster],write=[write],all=[all]]