apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: chaska-access-logs
  labels:
    strimzi.io/cluster: kafka-logging
spec:
  partitions: 3
  replicas: 2
  config:
    #120hr
    retention.ms: 432000000
    #1GiB
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: hillsboro-access-logs
  labels:
    strimzi.io/cluster: kafka-logging
spec:
  partitions: 3
  replicas: 2
  config:
    #120hr
    retention.ms: 432000000
    #1GiB
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: centralus-azure-access-logs
  labels:
    strimzi.io/cluster: kafka-logging
spec:
  partitions: 3
  replicas: 2
  config:
    #120hr
    retention.ms: 432000000
    #1GiB
    segment.bytes: 1073741824
