apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-logging
spec:
  kafka:
    resources:
      requests:
        memory: "1500Mi"
        cpu: "100m"
    jvmOptions:
      -Xms: 768m
      -Xmx: 768m
    version: 3.0.0
    replicas: 3
    listeners:
      - name: plain
        port: 9095
        type: internal
        tls: false
      - name: tls
        port: 9096
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9097
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30030
          brokers:
          - broker: 0
            nodePort: 30021
          - broker: 1
            nodePort: 30022
          - broker: 2
            nodePort: 30023
    config:
        auto.create.topics.enable: "false"
        offsets.topic.replication.factor: 3
        transaction.state.log.replication.factor: 3
        transaction.state.log.min.isr: 2
        message.max.bytes: 10485760  
        default.replication.factor: 3
        log.message.format.version: "3.0"
        inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 300Gi
        deleteClaim: false
        class: hpe-nimble-chaska-prod-delete
      
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml

    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - kafka
                topologyKey: kubernetes.io/hostname

  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 500Mi
        cpu: "30m"
      limits:
        memory: 2Gi
        cpu: "300m"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
      class: hpe-nimble-chaska-prod-delete
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yaml
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - zookeeper
                topologyKey: kubernetes.io/hostname
  entityOperator:
    topicOperator: 
      resources:
        requests:
          memory: 768Mi
          cpu: "100m"
        limits:
          memory: 768Mi
          cpu: "500m"
    userOperator: 
      resources:
        requests:
          memory: 768Mi
          cpu: "100m"
        limits:
          memory: 768Mi
          cpu: "500m"
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"

