apiVersion: v1
data:
  add-headers: ingress-nginx/custom-headers
  body-size: 64m
  enable-real-ip: "true"
  enable-underscores-in-headers: "true"
  hsts: "true"
  hsts-include-subdomains: "false"
  hsts-max-age: "31536000"
  http-snippet: |-
    map $http_cookie $auth_cookie {
      default "";
      "~ac=(?<token>.+)" "$token";
    }
  location-snippet: |-
    # CHRCSS-21688 & CHRCSS-28118 - Block ip address from scraping services
    deny 3.139.239.174;
    deny 3.141.14.104;
    deny 3.145.210.182;
    deny 3.234.236.178;
    deny 18.220.93.103;
    deny 34.217.1.29;
    deny 34.227.7.159;
    deny 35.85.28.211;
    deny 35.165.132.190;
    deny 35.171.167.223;
    deny 35.175.176.79;
    deny 44.210.103.150;
    deny 54.70.162.106;
    deny 54.89.148.168;
    deny 54.184.225.194;
    deny 54.201.190.1;
    deny 54.221.159.104;
    deny 73.11.240.49;
    # 2023-11-02
    deny 2.56.191.140;
    deny 2.104.55.23;
    deny 2.122.6.206;
    deny 3.16.124.102;
    deny 3.80.171.126;
    deny 3.143.210.129;
    deny 35.87.140.207;
    deny 54.211.182.239;
    # below is "hostb" - cannot block
    #    deny 104.42.175.191;
    # Additional Scraping IPs found in CHRCSS-30560
    deny 52.2.84.253;
    deny 177.227.29.91;
  log-format-escape-json: "true"
  log-format-upstream: '{"nginx":{"namespace":"$namespace","host":"$host","proxy_protocol_addr":"$proxy_protocol_addr","remote_addr":"$remote_addr","proxy_add_x_forwarded_for":"$proxy_add_x_forwarded_for","remote_user":"$remote_user","time_local":"$time_local","request_method":"$request_method","request":"$request","status":"$status","body_bytes_sent":"$body_bytes_sent","http_referer":"$http_referer","http_user_agent":"$http_user_agent","request_length":"$request_length","request_time":"$request_time","proxy_upstream_name":"$proxy_upstream_name","upstream_addr":"$upstream_addr","upstream_response_length":"$upstream_response_length","upstream_response_time":"$upstream_response_time","upstream_status":"$upstream_status","uri":"$uri","request_uri":"$request_uri","query_params":"$args","geoip":{"location":{"lat":"0","lon":"0"},"region_name":"","city_country_name":"","city":"","city_country_code":""},"realip_remote_addr":"$realip_remote_addr"}}'
  proxy-body-size: 900m
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-real-ip-cidr: "2.16.0.0/13,23.0.0.0/12,23.192.0.0/11,23.32.0.0/11,23.64.0.0/14,23.72.0.0/13,69.192.0.0/16,72.246.0.0/15,88.221.0.0/16,92.122.0.0/15,95.100.0.0/15,96.16.0.0/15,96.6.0.0/15,104.64.0.0/10,118.214.0.0/16,173.222.0.0/15,184.24.0.0/13,184.50.0.0/15,184.84.0.0/14,172.16.0.0/16,192.168.0.0/16"
  proxy-send-timeout: "600"
  server-name-hash-bucket-size: "256"
  use-geoip2: "true"
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
