kind: Secret
apiVersion: v1
metadata:
  name: catalog-elastic-users
stringData:
  users: |-
    developer:$2a$10$RaPffqtb3LQjlJiizGwy1unKt1up4yZMZft2iOWB99J3kd2PTAkyW
  users_roles: |-
    superuser:developer
