apiVersion: management.cattle.io/v3
builtin: false
context: cluster
description: 'Read-only access across the cluster.'
displayName: Cluster Read Only
external: false
hidden: false
kind: RoleTemplate
metadata:
  annotations:
    cleanup.cattle.io/rtUpgradeCluster: 'true'
    lifecycle.cattle.io/create.mgmt-auth-roletemplate-lifecycle: 'true'
  finalizers:
    - controller.cattle.io/mgmt-auth-roletemplate-lifecycle
  generateName: rt-
  labels:
    cattle.io/creator: kustom-infrastructure
  name: rt-cluster-read-only
rules:
  - apiGroups:
      - ''
    resources:
      - pod
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - api
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - projectroletemplatebindings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - project.cattle.io
    resources:
      - apps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - project.cattle.io
    resources:
      - apps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - project
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - clusterevents
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
