---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catalog

bases:
  - ../../../../bases/kafka-strimzi/stage2/

resources:
  - elasticsearch.yaml
  - kibana.yaml
  - ingress.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: prometheus
  path: patches/set-cluster-role.yaml
