---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catalog

resources:
  - namespace.yaml
  - resources/
  - ../../../../bases/kafka-strimzi/stage1/
  - ../../resources/ssl-secrets/

generators:
  - generators/azure-credentials.yaml
  - generators/catalog-secrets.yaml
  - generators/catalog-es-http-certs-public-hillsboro.yaml

patches:
  # Since we do not apply the same namespace to everything, we need to patch it
  # to the generated ssl secret.
  - target:
      name: fcaus-wildcard
      kind: Secret
    patch: |-
      - op: add
        path: /metadata/namespace
        value: catalog
