#!/bin/bash
# For development purposes, set BASEDIR to the full path of the kustom
# directory, e.g.  BASEDIR=~/git/fcaus/support/kustom
if [ "${BASEDIR}" != "" ]
then
  source ${BASEDIR}/plugin/fca.autodata.net/v1/parse-yaml.sh
  source ${BASEDIR}/plugin/fca.autodata.net/v1/thycotic.sh
else
  source $(dirname $0)/../parse-yaml.sh
  source $(dirname $0)/../thycotic.sh
fi

create_variables $1

REGISTRATION_TOKEN='""'
if [ "${registration_secret}" != "" ]
then
  REGISTRATION_TOKEN=$(get_secret ${registration_secret} password password | tr -d '"' | openssl base64 -A)
fi
RUNNER_TOKEN='""'
if [ "${runner_secret}" != "" ]
then
  RUNNER_TOKEN=$(get_secret ${runner_secret} password password | tr -d '"' | openssl base64 -A)
fi

echo "apiVersion: v1"
echo "kind: Secret"
echo "metadata:"
echo "  name: ${metadata_name}"
echo "data:"
echo "  runner-registration-token: ${REGISTRATION_TOKEN}"
echo "  runner-token: ${RUNNER_TOKEN}"
