{
 "title": "Dashboard Chaska Storage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ElasticsearchDS", "label": "Elastic Search Data Source", "query": "elasticsearch" }
  ]
 },
 "panels": [
  {
   "title": "www / stage Traffic Chaska (req/min)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "chaska stage",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "nginx.namespace:stage AND photon.datacenter:Chaska",
     "timeField": "@timestamp"
    },
    {
     "alias": "chaska www",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "nginx.namespace:www AND photon.datacenter:Chaska",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "www / Stage Traffic Hillsboro (req/min)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "hillsboro stage",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "nginx.namespace:stage AND photon.datacenter:Hillsboro",
     "timeField": "@timestamp"
    },
    {
     "alias": "hillsboro www",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "nginx.namespace:www AND photon.datacenter:Hillsboro",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Services with CPU Throttled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{container!=\"\",namespace!=\"monitoring\"}[5m])) / sum by(container, pod, namespace) (increase(container_cpu_cfs_periods_total[5m])) > 0.1",
     "legendFormat": "{{namespace}}-{{container}}"
    }
   ]
  },
  {
   "title": "Percentile Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "nginx.upstream_response_time",
       "id": "1",
       "meta": {},
       "settings": {
        "percents": [
         "90",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "nginx.namespace:\"www\" OR nginx.namespace:\"stage\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Slow Query (PRDM-XMY1-6)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\nlabel_replace(\n  label_replace(\n    label_replace(\n      label_replace(\n        label_replace(\n          label_replace(\n            label_replace(\n            label_replace(\n            label_replace(\n            label_replace(\n            label_replace(rate(mysql_global_status_slow_queries{instance=~\"10.0.32.93:9104|10.0.32.94:9104|10.0.32.98:9104|10.0.32.97:9104|10.0.32.96:9104|10.0.32.99:9104|10.0.32.100:9104|10.0.32.101:9104|10.0.32.121:9104|10.0.32.122:9104|10.0.32.123:9104|10.0.32.124:9104|10.0.32.131:9104|10.0.32.132:9104|10.0.32.170:9104|10.0.32.171:9104|10.0.32.42:9104|10.0.32.43:9104|10.0.32.172:9104\"}[1m]),\n              \"short_instance\", \"$1\", \"instance\", \"(.*):.*\"\n            ),\n            \"hostname\",\"fchu-prdm-xmys1\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.96.*\"\n          ),\n          \"hostname\",\"fchu-prdm-xmys2\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.97.*\"\n        ),\n        \"hostname\",\"fchu-prdm-xmys3\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.98.*\"\n      ),\n      \"hostname\",\"fchu-prdm-xmys4\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.99.*\"\n    ),\n    \"hostname\",\"fchu-prdm-xmys5\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.100.*\"\n  ),\n  \"hostname\",\"fchu-prdm-xmys6\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.101.*\"\n),\n          \"hostname\",\"fchu-prmo-xmy1\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.121.*\"\n        ),\n          \"hostname\",\"fchu-prmo-xmy2\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.122.*\"\n        ),\n          \"hostname\",\"fchu-prmo-xmys1\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.123.*\"\n        ),\n          \"hostname\",\"fchu-prmo-xmys2\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.124.*\"\n        )        ,\n          \"hostname\",\"fchu-prdm-xmy1\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.93.*\"\n        ),\n          \"hostname\",\"fchu-prdm-xmy2\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.94.*\"\n        ),\n      \"hostname\",\"fchu-prmo-xmys3\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.131.*\"\n     ),\n    \"hostname\",\"fchu-prmo-xmys4\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.132.*\"\n     ),\n    \"hostname\",\"fchu-prif-xmy1\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.170.*\"\n     ),\n    \"hostname\",\"fchu-prif-xmys1\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.171.*\"\n     ),\n    \"hostname\",\"fchu-prif-xmys2\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.42.*\"\n     ),\n    \"hostname\",\"fchu-prif-xmys3\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.43.*\"\n     ),\n    \"hostname\",\"fchu-teif-xmy1\",\"short_instance\",\"10\\\\.0\\\\.32\\\\.172.*\"\n     )\n        ",
     "legendFormat": "{{hostname}} {{short_instance}}"
    }
   ]
  },
  {
   "title": "Avg Response/Request Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Avg Response Time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "nginx.upstream_response_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "NOT nginx.host:etl-mail.fcausf.autodata.tech AND NOT nginx.namespace:monitoring",
     "timeField": "@timestamp"
    },
    {
     "alias": "Avg Request Time",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "nginx.request_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "NOT nginx.host:etl-mail.fcausf.autodata.tech AND NOT nginx.namespace:monitoring",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}