---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incentives-elastic

resources:
  - backup-pvc.yaml
  - certs/incentives-certs.yaml
  - secrets/incentives-elastic-users.yaml
