#!/bin/bash
# For development purposes, set BASEDIR to the full path of the kustom
# directory, e.g.  BASEDIR=/home/peterj/kustom go test
if [ "${BASEDIR}" != "" ]
then
  source ${BASEDIR}/plugin/fca.autodata.net/v1/parse-yaml.sh
  source ${BASEDIR}/plugin/fca.autodata.net/v1/thycotic.sh
else
  source $(dirname $0)/../parse-yaml.sh
  source $(dirname $0)/../thycotic.sh
fi

create_variables $1

set -e -o pipefail
while IFS= read -r line
do
  if [[ $line =~ __SECRET__ ]]
  then
    SECRET_ID=$(echo $line | sed 's .*__SECRET__\(\w\+\):.* \1 ')
    SECRET_FIELD=$(echo $line | sed 's .*__SECRET__\w\+:\(\w\+\).* \1 ')
    THYCOTIC_VALUE=$(get_secret ${SECRET_ID} ${SECRET_FIELD} | tr -d '"' | sed 's/&/\\&/g')
    sed -e 's \(__SECRET__\w\+:\w\+\) '"${THYCOTIC_VALUE}"' ' <<<"$line"
  else
    echo "$line"
  fi
done </dev/stdin
