#!/usr/bin/env bash
# For development purposes, set BASEDIR to the full path of the kustom
# directory, e.g.  BASEDIR=~/git/fcaus/support/kustom
if [ "${BASEDIR}" != "" ]
then
  source ${BASEDIR}/plugin/fca.autodata.net/v1/parse-yaml.sh
  source ${BASEDIR}/plugin/fca.autodata.net/v1/thycotic.sh
else
  source $(dirname $0)/../parse-yaml.sh
  source $(dirname $0)/../thycotic.sh
fi

create_variables $1

SECRET_ID="${secret}"
PRIVATE_KEY=$(get_secret ${SECRET_ID} key ssl-certificate | openssl base64 -A)
PUBLIC_KEY=$(get_secret ${SECRET_ID} public-certificate ssl-certificate | openssl base64 -A)

cat <<EOF | cat 
apiVersion: v1
kind: Secret
metadata:
  name: "${metadata_name}"
  namespace: "${metadata_namespace}"
data:
  tls.crt: ${PUBLIC_KEY}
  tls.key: ${PRIVATE_KEY}
type: kubernetes.io/tls
EOF
