#!/bin/bash
# For development purposes, set BASEDIR to the full path of the kustom
# directory, e.g.  BASEDIR=~/git/fcaus/support/kustom
if [ "${BASEDIR}" != "" ]
then
  source ${BASEDIR}/plugin/fca.autodata.net/v1.1/parse-yaml.sh
  source ${BASEDIR}/plugin/fca.autodata.net/v1.1/thycotic.sh
else
  source $(dirname $0)/../parse-yaml.sh
  source $(dirname $0)/../thycotic.sh
fi

create_variables $1

if [ "${username_key}" = "" ]
then
  username_key=${username}
fi
if [ "${password_key}" = "" ]
then
  password_key=${password}
fi
if [ "${resource_key}" = "" ]
then
  resource_key=${resource}
fi

THYCOTIC_USERNAME=$(get_secret ${secret} username password | tr -d '"' | openssl base64 -A)
if [ "" != "${password_key}" ]; then
  THYCOTIC_PASSWORD=$(get_secret ${secret} password password | tr -d '"' | openssl base64 -A)
fi
if [ "" != "${resource_key}" ]; then
  THYCOTIC_RESOURCE=$(get_secret ${secret} resource password | tr -d '"' | openssl base64 -A)
fi

echo "apiVersion: v1"
echo "kind: Secret"
echo "metadata:"
echo "  name: ${metadata_name}"
if [ "" != "${metadata_namespace}" ]; then
  echo "  namespace: ${metadata_namespace}"
fi

if [ "" != "${username_key}" ] || [ "" != "${password_key}" ] || [ "" != "${resource_key}" ]; then
  echo "data:"
fi
if [ "" != "${username_key}" ]; then
  echo "  ${username_key}: ${THYCOTIC_USERNAME}"
fi
if [ "" != "${password_key}" ]; then
  echo "  ${password_key}: ${THYCOTIC_PASSWORD}"
fi
if [ "" != "${resource_key}" ]; then
  echo "  ${resource_key}: ${THYCOTIC_RESOURCE}"
fi
echo "stringData:"
echo "  serviceName: ${service_name}"
echo "  servicePort: ${service_port}"
# Assume backend is provided in secret generator definition when resource_key is not specified.
if [ "" = "${resource_key}" ]; then
  echo "  backend: ${backend}"
fi
