apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: nginx-ingress-serviceaccount
  name: nginx-ingress-serviceaccount-token
type: kubernetes.io/service-account-token
