{
 "title": "HPE Storage Volume Details",
 "description": "Provides a drill-down overview of a volume.",
 "tags": [ "HPE Storage Volume Details" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "array", "label": "Array", "query": { "query": "label_values(array)" } },
   { "name": "pool", "label": "Pool", "query": "default" },
   {
    "name": "volume_name",
    "label": "Volume Name",
    "query": {
     "query": "label_values(hpe_volume_used_bytes{pool=\"$pool\", array=\"$array\"}, volume_name)"
    }
   },
   {
    "name": "volume",
    "label": "Volume",
    "query": {
     "query": "label_values(hpe_volume_used_bytes{pool=\"$pool\", array=\"$array\", volume_name=\"$volume_name\"}, volume)"
    }
   },
   {
    "name": "pvc_namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(hpestoragecsi_volume_info{pv=\"$volume_name\"}, pvc_namespace)"
    }
   },
   {
    "name": "pvc_name",
    "label": "Persistent Volume Claim",
    "query": {
     "query": "label_values(hpestoragecsi_volume_info{pv=\"$volume_name\"}, pvc_name)"
    }
   },
   {
    "name": "pvc_storageclass",
    "label": "Storage Class",
    "query": {
     "query": "label_values(hpestoragecsi_volume_info{pv=\"$volume_name\"}, storage_class)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Information",
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "|  |  |\n| ----------- | -------------- |\n| Volume | ${volume} |\n| Volume Name | ${volume_name} |\n| Namespace | ${pvc_namespace} |\n| Name | ${pvc_name} |\n| Storage Class | ${pvc_storageclass} | "
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hpe_volume_size_bytes{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "hpe_volume_used_bytes{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "hpe_volume_snapshot_used_bytes{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Snapshot Used"
    }
   ]
  },
  {
   "title": "Max Read Throughput (5m avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "hpe_volume_read_bytes_per_second_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Max Read Throughput"
    }
   ]
  },
  {
   "title": "Max Write Throughput (5m avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "hpe_volume_write_bytes_per_second_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Max Write Throughput"
    }
   ]
  },
  {
   "title": "Volume Read Performance (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hpe_volume_reads_per_second_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "IOPS"
    },
    {
     "expr": "hpe_volume_seconds_per_read_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Volume Write Performance (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hpe_volume_writes_per_second_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "IOPS"
    },
    {
     "expr": "hpe_volume_seconds_per_write_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Volume Latency Heatmap (5m avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "hpe_volume_seconds_per_write_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "hpe_volume_seconds_per_read_avg5m{array=\"$array\", volume=\"$volume\",storagepool=\"$pool\"}",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}