global:
  resolve_timeout: 5m
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  - equal:
      - namespace
    source_matchers:
      - "alertname = InfoInhibitor"
    target_matchers:
      - "severity = info"
receivers:
  - name: Default
  - name: Critical
  - name: Watchdog
  - name: "null"
  - name: teams-chat-prod
    webhook_configs:
      - url: http://prom2teams-prod.monitoring.svc:8080/alerts
  - name: teams-chat
    webhook_configs:
      - url: http://prom2teams.monitoring.svc:8080/alerts
route:
  group_by: [namespace, job]
  group_interval: 5m
  group_wait: 30s
  receiver: teams-chat-prod
  repeat_interval: 12h
  routes:
    - match:
        alertname: Watchdog
      receiver: Watchdog
    - match:
        severity: critical
      receiver: Critical
    - match_re:
        namespace: test|test2
      receiver: teams-chat
    - match:
        alertname: InfoInhibitor
      receiver: "null"
