{
 "title": "Incentives - Sink",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Change Processing Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(incentives_incentives_mysql_sink_changes_handled{namespace=\"$namespace\",pod=\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Offering Changes Histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "incentives_incentives_mysql_sink_change_duration_seconds_bucket{topic=~\".*-offering-changestream\",type=\"changed\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Program Changes Histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "incentives_incentives_mysql_sink_change_duration_seconds_bucket{topic=~\".*-program-changestream\",type=\"changed\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Offering Deletes Histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "incentives_incentives_mysql_sink_change_duration_seconds_bucket{topic=~\".*-offering-changestream\",type=\"deleted\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Program Deletes Histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "incentives_incentives_mysql_sink_change_duration_seconds_bucket{topic=~\".*-program-changestream\",type=\"deleted\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Offering Average Transaction Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "incentives_incentives_mysql_sink_change_duration_seconds_sum{topic=~\".*-offering-changestream\",namespace=\"$namespace\",pod=\"$pod\"} / incentives_incentives_mysql_sink_change_duration_seconds_count{topic=~\".*-offering-changestream\",namespace=\"$namespace\",pod=\"$pod\"}\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Program Average Transaction Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "incentives_incentives_mysql_sink_change_duration_seconds_sum{topic=~\".*-program-changestream\",namespace=\"$namespace\",pod=\"$pod\"} / incentives_incentives_mysql_sink_change_duration_seconds_count{topic=~\".*-program-changestream\",namespace=\"$namespace\",pod=\"$pod\"}\n",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}