---
apiVersion: v1
kind: Namespace
metadata:
  name: inventory

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: inventory
  namespace: inventory
spec:
  version: 7.16.3
  auth:
    fileRealm:
    - secretName: inventory-elastic-users
  # monitoring:
  #   metrics:
  #     elasticsearchRefs:
  #     - name: eckmon
  #       namespace: eckmon
  #   logs:
  #     elasticsearchRefs:
  #     - name: eckmon
  #       namespace: eckmon
  http:
    tls:
      certificate:
        secretName: inventory-es-cert
    service:
      spec:
        type: NodePort
        ports:
          - name: https
            nodePort: 30091
            port: 9200
            protocol: TCP
            targetPort: 9200
        selector:
          elasticsearch.k8s.elastic.co/cluster-name: "inventory"
          elasticsearch.k8s.elastic.co/node-master: "false"
  secureSettings:
  - secretName: azure-credentials
    entries:
    - key: blobstore-accountname
      path: azure.client.default.account
    - key: blobstore-key
      path: azure.client.default.key
  nodeSets:
  - name: inventory-master-hpe
    count: 3
    config:
      xpack:
        security:
          enabled: true
          authc.realms.file.file1.order: 0
      http:
        compression: true
        compression_level: 8
      transport:
        compress: true
      node.roles: ["master"]
      reindex.remote.whitelist: "inventory-search.fcaus-p-storage.autodata.tech:30091"
      reindex.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates-source/tls.crt"
    volumeClaimTemplates:
    - metadata: 
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64Mi
        storageClassName: hpe-nimble-chaska-prod-retain
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin remove --purge repository-s3 prometheus-exporter repository-azure
            bin/elasticsearch-plugin install -b repository-s3 https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/7.16.3.0/prometheus-exporter-7.16.3.0.zip
            bin/elasticsearch-plugin install -b https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-azure/repository-azure-7.16.3.zip
        - name: take-nfs-ownership
          command:
          - chown
          - -R
          - 1000:1000
          - /usr/share/elasticsearch/backup
          volumeMounts:
          - name: elastic-backup
            mountPath:  /usr/share/elasticsearch/backup
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms500m -Xmx500m
          - name: path.repo
            value:  /usr/share/elasticsearch/backup
          resources:
            requests:
              memory: 1Gi
              cpu: "250m"
            limits:
              memory: 1Gi
              cpu: 2
          volumeMounts:
          - name: elastic-cert-hillsboro
            mountPath: /usr/share/elasticsearch/config/certificates-source
          - name: elastic-backup
            mountPath: /usr/share/elasticsearch/backup
        volumes:
        - name: elastic-cert-hillsboro
          secret:
            secretName: inventory-es-http-certs-public-hillsboro
        - name: elastic-backup
          persistentVolumeClaim:
            claimName: elastic-backup-pvc
  - name: inventory-data-hpe-50g
    count: 3
    config:
      http:
        compression: true
        compression_level: 9
      transport:
        compress: true
      node.roles: ["data", "ingest", "transform"]
      reindex.remote.whitelist: "inventory-search.fcaus-p-storage.autodata.tech:30091"
      reindex.ssl.certificate_authorities: "/usr/share/elasticsearch/config/certificates-source/tls.crt"
    volumeClaimTemplates:
    - metadata: 
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 80Gi
        storageClassName: hpe-nimble-chaska-prod-retain
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin remove --purge repository-s3 prometheus-exporter repository-azure
            bin/elasticsearch-plugin install -b repository-s3 https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/7.16.3.0/prometheus-exporter-7.16.3.0.zip
            bin/elasticsearch-plugin install -b https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-azure/repository-azure-7.16.3.zip
        - name: take-nfs-ownership
          command:
          - chown
          - -R
          - 1000:1000
          - /usr/share/elasticsearch/backup
          volumeMounts:
          - name: elastic-backup
            mountPath:  /usr/share/elasticsearch/backup
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2000m -Xmx2000m
          - name: path.repo
            value:  /usr/share/elasticsearch/backup
          resources:
            requests:
              memory: 4Gi
              cpu: "250m"
            limits:
              memory: 4Gi
              cpu: 2
          volumeMounts:
          - name: elastic-cert-hillsboro
            mountPath: /usr/share/elasticsearch/config/certificates-source
          - name: elastic-backup
            mountPath: /usr/share/elasticsearch/backup
        volumes:
        - name: elastic-cert-hillsboro
          secret:
            secretName: inventory-es-http-certs-public-hillsboro
        - name: elastic-backup
          persistentVolumeClaim:
            claimName: elastic-backup-pvc
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: inventory
  namespace: inventory
spec:
  version: 7.16.3
  count: 1
  config:
    #override default so kib loads more info on options
    kibana.autocompleteTerminateAfter: "2000000"
    server.publicBaseUrl: "https://inventory.fcaus-f-storage.autodata.tech"
  elasticsearchRef:
    name: inventory
    namespace: inventory
  # monitoring:
  #   metrics:
  #     elasticsearchRefs:
  #     - name: eckmon
  #       namespace: eckmon
  #   logs:
  #     elasticsearchRefs:
  #     - name: eckmon
  #       namespace: eckmon

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: inventory
  labels:
    app: kibana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  rules:
    - host: inventory.fcaus-f-storage.autodata.tech
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: inventory-kb-http
                port:
                  number: 5601
  tls:
    - secretName: fcaus-wildcard
      hosts:
        - inventory.fcaus-f-storage.autodata.tech
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: inventory
  labels:
    app: elasticsearch
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  rules:
    - host: inventory-search.fcaus-f-storage.autodata.tech
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: inventory-es-http
                port:
                  number: 9200
  tls:
    - secretName: inventory-es-cert
      hosts:
        - inventory-search.fcaus-f-storage.autodata.tech
