#!/bin/bash
# For development purposes, set BASEDIR to the full path of the kustom
# directory, e.g.  BASEDIR=~/git/fcaus/support/kustom
if [ "${BASEDIR}" != "" ]
then
  source ${BASEDIR}/plugin/fca.autodata.net/v1.1/parse-yaml.sh
  source ${BASEDIR}/plugin/fca.autodata.net/v1.1/thycotic.sh
else
  source $(dirname $0)/../parse-yaml.sh
  source $(dirname $0)/../thycotic.sh
fi

create_variables $1

httpPort="${ports_http:-15672}"
amqpPort="${ports_amqp:-5672}"

THYCOTIC_USERNAME=$(get_secret ${secret} username password | tr -d '"' | openssl base64 -A)
THYCOTIC_PASSWORD=$(get_secret ${secret} password password | tr -d '"' | openssl base64 -A)
THYCOTIC_RESOURCE_RAW=$(get_secret ${secret} resource password | tr -d '"')
# split the resource into its parts separated by a slash
THYCOTIC_RESOURCE_START=$(echo ${THYCOTIC_RESOURCE_RAW} | cut -d/ -f1)
THYCOTIC_RESOURCE_END=$(echo ${THYCOTIC_RESOURCE_RAW} | cut -d/ -f2)
# if the second element of the resource is empty, set it to a slash by default
if [ "${THYCOTIC_RESOURCE_END}" == "" ]
then
  THYCOTIC_RESOURCE_END="/";
fi

amqpHost="${host:-${THYCOTIC_RESOURCE_START:-rabbitmq}}"
amqpVHost="${vhost:-${THYCOTIC_RESOURCE_END:-/}}"

echo "apiVersion: v1"
echo "kind: Secret"
echo "metadata:"
echo "  name: ${metadata_name}"
echo "data:"
echo "  rabbitmq-user: ${THYCOTIC_USERNAME}"
echo "  rabbitmq-host: $(echo -n "${amqpHost}" | openssl base64 -A)"
echo "  rabbitmq-port: $(echo -n "${amqpPort}" | openssl base64 -A)"
echo "  rabbitmq-http-port: $(echo -n "${httpPort}" | openssl base64 -A)"
echo "  rabbitmq-password: ${THYCOTIC_PASSWORD}"
echo "  rabbitmq-vhost: $(echo -n "${amqpVHost}" | openssl base64 -A)"
echo "  rabbitmq-vhost-escaped: $(echo -n "${amqpVHost////%2F}" | openssl base64 -A)"
echo "  username: ${THYCOTIC_USERNAME}"
echo "  password: ${THYCOTIC_PASSWORD}"
