apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: rke2-ingress-nginx
  namespace: kube-system
  releaseName: rke2-ingress-nginx
  repo: https://github.com/rancher/rke2-charts/raw/main/
  valuesInline:
    controller:
      admissionWebhooks:
        enabled: false
      allowSnippetAnnotations: true
      image:
        pullPolicy: IfNotPresent
      kind: DaemonSet
      livenessProbe:
        initialDelaySeconds: 100
      resources:
        limits:
          cpu: 4000m
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true
  version: 4.10.401
resources:
- configMaps/custom-headers.yaml
patches:
- path: configMaps/rke2-ingress-nginx-controller-patch.yaml
