kind: Secret
apiVersion: v1
metadata:
  name: inventory-elastic-users
stringData:
  users: |-
    inventory:$2b$04$zPd4xz6w58SY.T7hVyW2Je7gzU1zLjHab03aPCONquxJ2v4UQZXcK
  users_roles: |-
    superuser:inventory
