apiVersion: v1
data:
  add-headers: kube-system/custom-headers
  body-size: 64m
  enable-real-ip: "true"
  enable-underscores-in-headers: "true"
  hsts: "true"
  hsts-include-subdomains: "false"
  hsts-max-age: "31536000"
  http-snippet: |-
    map $http_cookie $auth_cookie {
      default "";
      "~ac=(?<token>.+)" "$token";
    }
    # List of IP addresses to deny
    map $remote_addr $deny_ip {
      default 0;
      3.139.239.174 1;
      3.141.14.104 1;
      3.145.210.182 1;
      3.234.236.178 1;
      18.220.93.103 1;
      34.217.1.29 1;
      34.227.7.159 1;
      35.85.28.211 1;
      35.165.132.190 1;
      35.171.167.223 1;
      35.175.176.79 1;
      44.210.103.150 1;
      54.70.162.106 1;
      54.89.148.168 1;
      54.184.225.194 1;
      54.201.190.1 1;
      54.221.159.104 1;
      73.11.240.49 1;
      2.56.191.140 1;
      2.104.55.23 1;
      2.122.6.206 1;
      3.16.124.102 1;
      3.80.171.126 1;
      3.143.210.129 1;
      35.87.140.207 1;
      54.211.182.239 1;
      177.227.29.91 1;
    }
    # List of conditionally denied IP addresses
    map $remote_addr $conditionally_deny_ip {
      default 0;
      54.88.83.195 1;
      54.164.93.60 1;
    }
    # List of conditionally denied user agents
    map $http_user_agent $conditionally_deny_user_agent {
      default 0;
      "~*Dealer-Inspire-Stellantis" 1;
    }
  location-snippet: |-
    if ($deny_ip) {
      return 403;
    }
#    if ($conditionally_deny_ip) { # Comment or uncomment this block as needed
#      return 403;
#    }
#    if ($conditionally_deny_user_agent) { # Comment or uncomment this block as needed
#      return 403;
#    }
  log-format-escape-json: "true"
  log-format-upstream: '{"nginx":{"namespace":"$namespace","host":"$host","proxy_protocol_addr":"$proxy_protocol_addr","remote_addr":"$remote_addr","proxy_add_x_forwarded_for":"$proxy_add_x_forwarded_for","remote_user":"$remote_user","time_local":"$time_local","request_method":"$request_method","request":"$request","status":"$status","body_bytes_sent":"$body_bytes_sent","http_referer":"$http_referer","http_user_agent":"$http_user_agent","request_length":"$request_length","request_time":"$request_time","proxy_upstream_name":"$proxy_upstream_name","upstream_addr":"$upstream_addr","upstream_response_length":"$upstream_response_length","upstream_response_time":"$upstream_response_time","upstream_status":"$upstream_status","uri":"$uri","request_uri":"$request_uri","query_params":"$args","geoip":{"location":{"lat":"0","lon":"0"},"region_name":"","city_country_name":"","city":"","city_country_code":""},"realip_remote_addr":"$realip_remote_addr"}}'
  proxy-body-size: 900m
  proxy-connect-timeout: "15"
  proxy-read-timeout: "600"
  proxy-real-ip-cidr: "2.16.0.0/13,23.0.0.0/12,23.192.0.0/11,23.32.0.0/11,23.64.0.0/14,23.72.0.0/13,69.192.0.0/16,72.246.0.0/15,88.221.0.0/16,92.122.0.0/15,95.100.0.0/15,96.16.0.0/15,96.6.0.0/15,104.64.0.0/10,118.214.0.0/16,173.222.0.0/15,184.24.0.0/13,184.50.0.0/15,184.84.0.0/14,172.16.0.0/16,192.168.0.0/16"
  proxy-send-timeout: "600"
  server-name-hash-bucket-size: "256"
  use-geoip2: "true"
kind: ConfigMap
metadata:
  name: rke2-ingress-nginx-controller
  namespace: kube-system
