---
apiVersion: v1
kind: Namespace
metadata:
  name: eckmon
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eckmon
  namespace: eckmon
spec:
  version: 7.16.3
  http:
    tls:
      certificate:
        secretName: eckmon-es-cert
  nodeSets:
    - name: default
      count: 1
      config:
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 200Gi
            storageClassName: hpe-nimble-chaska-prod-retain
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                  cpu: 1
                limits:
                  memory: 2Gi
                  cpu: 1

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: eckmon
  namespace: eckmon
spec:
  version: 7.16.3
  count: 1
  elasticsearchRef:
    name: eckmon
  config:
    server.publicBaseUrl: "https://eckmon.fcaus-f-storage.autodata.tech"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: eckmon
  labels:
    app: kibana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_ssl_verify off;
spec:
  rules:
    - host: eckmon.fcaus-f-storage.autodata.tech
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: eckmon-kb-http
                port:
                  number: 5601
  tls:
    - secretName: fcaus-wildcard
      hosts:
        - eckmon.fcaus-f-storage.autodata.tech
