kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_consistent_hash_exchange
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_shovel
      - rabbitmq_shovel_management
  image: bitnami/rabbitmq:3.10
  persistence:
    storageClassName: hpe-nimble-chaska-prod-delete
    storage: 10Gi
