---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incentives-elastic

resources:
  - namespace.yaml
  - resources/
  - ../../resources/ssl-secrets/

generators:
  - generators/azure-credentials.yaml
  - generators/incentives-es-http-certs-public-hillsboro.yaml
  - generators/incentives-secrets.yaml

patches:
  # Since we do not apply the same namespace to everything, we need to patch it
  # to the generated ssl secret.
  - target:
      name: fcaus-wildcard
      kind: Secret
    patch: |-
      - op: add
        path: /metadata/namespace
        value: incentives-elastic
