apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: akhq
      app.kubernetes.io/name: akhq
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: akhq
        app.kubernetes.io/name: akhq
    spec:
      containers:
      - image: tchiotludo/akhq:0.20.0
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: management
        name: akhq
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 28081
          name: management
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: management
        volumeMounts:
        - mountPath: /app/application.yml
          name: config
          subPath: application.yml
      serviceAccountName: default
      volumes:
      - name: config
        configMap:
          name: akhq
          items:
            - key: akhq-application.yml
              path: application.yml
