{
 "title": "HPE Storage Array Details",
 "description": "Provides a birds eye view of a HPE storage array.",
 "tags": [ "HPE Storage Array Details" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "array", "label": "Array", "query": { "query": "label_values(array)" } }
  ]
 },
 "panels": [
  {
   "title": "Volume IOPS (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(hpe_volume_reads_per_second_avg5m{array=\"$array\"})",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(hpe_volume_writes_per_second_avg5m{array=\"$array\"})",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Avg. Read Latency (5min avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hpe_volume_seconds_per_read_avg5m{array=\"$array\"})",
     "legendFormat": "Seconds per Read"
    }
   ]
  },
  {
   "title": "Avg. Write Latency (5min avg)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hpe_volume_seconds_per_write_avg5m{array=\"$array\"})",
     "legendFormat": "Seconds per Write"
    }
   ]
  },
  {
   "title": "Pool Capacities (total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(hpe_storagepool_volume_used_bytes{array=\"$array\"})",
     "legendFormat": "Pre-reduction Volume Usage"
    },
    {
     "expr": "sum(hpe_storagepool_capacity_bytes{array=\"$array\"})",
     "legendFormat": "Total Capacity"
    },
    {
     "expr": "sum(hpe_storagepool_unused_reserve_bytes{array=\"$array\"})",
     "legendFormat": "Unused Reserve"
    },
    {
     "expr": "sum(hpe_storagepool_snapshot_used_bytes{array=\"$array\"})",
     "legendFormat": "Pre-reduction Snapshot Usage"
    },
    {
     "expr": "sum(hpe_storagepool_data_reduction_bytes{array=\"$array\"})",
     "legendFormat": "Data Reduction"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "expression": "$volume_used - $data_reduction",
     "type": "math"
    }
   ]
  },
  {
   "title": "Volume Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(hpe_volume_size_bytes{array=\"$array\"})",
     "legendFormat": "Volume Count"
    }
   ]
  },
  {
   "title": "Array Latency Heat Map (5min avg)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "hpe_volume_seconds_per_write_avg5m{array=\"$array\"}",
     "legendFormat": "Seconds per Write"
    },
    {
     "expr": "hpe_volume_seconds_per_read_avg5m{array=\"$array\"}",
     "legendFormat": "Seconds per Read"
    }
   ]
  }
 ]
}