apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  serviceName: logstash
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      name: logstash
      labels:
        app: logstash
    spec:
      terminationGracePeriodSeconds: 120
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                  - "logstash"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.16.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 3
        ports:
        - name: http
          containerPort: 9600
        resources:
          requests:
            cpu: "100m"
            memory: "1536Mi"
          limits:
            cpu: "1000m"
            memory: "1536Mi"
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        volumeMounts:
        - name: logstashconfig
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: logstashconfig
          mountPath: /usr/share/logstash/config/pipelines.yml
          subPath: pipelines.yml
        - name: logstashpipeline
          mountPath: /usr/share/logstash/pipelines
      volumes:
        - name: logstashconfig
          configMap:
            name: logstash-config
            items:
            - key: logstash.yml
              path: logstash.yml
            - key: pipelines.yml
              path: pipelines.yml
        - name: logstashpipeline
          configMap:
            name: logstash-pipeline
            items:
            - key: pipeline-access-logs.conf
              path: pipeline-access-logs.conf
            - key: pipeline-errors.conf
              path: pipeline-errors.conf
            - key: pipeline-application-logs.conf
              path: pipeline-application-logs.conf
            # - key: pipeline-dead-letter.conf
            #   path: pipeline-dead-letter.conf
