resources:
  - namespace.yaml
helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io/
    valuesInLine:
      installCRDs: true
    version: v1.13.1
