---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: catalog
spec:
  version: 8.4.2
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: --max-old-space-size=2048
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2.5Gi
  count: 1
  config:
    #override default so kib loads more info on options
    kibana.autocompleteTerminateAfter: "2000000"
    server.publicBaseUrl: "https://catalog-kibana.fcaus-f-storage.autodata.tech"
    csp.strict: false
  elasticsearchRef:
    name: catalog
    namespace: catalog
