apiVersion: v1
kind: Secret
metadata:
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    [server]
    root_url = https://grafana.fcaus-f-storage.autodata.tech
