apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  labels:
    app.kubernetes.io/name: pushgateway
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pushgateway
    spec:
      containers:
        - name: prom-pushgw
          image: prom/pushgateway:v1.5.1
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9091
              name: metrics
