apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pushgateway
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pushgateway
  ports:
    - name: metrics
      port: 9091
      targetPort: metrics
