apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: eck-operator-crds
    releaseName: elastic-operator
    repo: https://helm.elastic.co/
    version: 2.5.0
