#-------------------------------------------------------------------------------
# cluster: fcaus-f
#-------------------------------------------------------------------------------

chaska-kube-turbo:
  environment:
    name: kube-turbo/chaska
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: deploy:chaska
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $FCAUS_CHASKA_DEPLOYER_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/chaska/kube-turbo/ | kubectl apply -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:chaska"
    - "du:stellantis-us"

undeploy:chaska-kube-turbo:
  environment:
    name: kube-turbo/chaska
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: undeploy:chaska
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $FCAUS_CHASKA_DEPLOYER_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/chaska/kube-turbo/ | kubectl delete -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:chaska"
    - "du:stellantis-us"

#-------------------------------------------------------------------------------
# cluster: fcaus-f-storage
#-------------------------------------------------------------------------------

chaska-storage-kube-turbo:
  environment:
    name: kube-turbo/chaska-storage
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: deploy:chaska-storage
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_CHASKA_STORAGE_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/chaska-storage/kube-turbo/ | kubectl apply -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:chaska"
    - "du:stellantis-us"

undeploy:chaska-storage-kube-turbo:
  environment:
    name: kube-turbo/chaska-storage
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: undeploy:chaska-storage
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_CHASKA_STORAGE_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/chaska-storage/kube-turbo/ | kubectl delete -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:chaska"
    - "du:stellantis-us"

#-------------------------------------------------------------------------------
# cluster: fcaus-ct-storage
#-------------------------------------------------------------------------------

ct-storage-kube-turbo:
  environment:
    name: kube-turbo/continuous-testing-storage
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: deploy:continuous-testing-storage
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_CT_STORAGE_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/ct-storage/kube-turbo/ | kubectl apply -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:london"
    - "du:stellantis-us"
    - "cluster:ct-storage"

undeploy:ct-storage-kube-turbo:
  environment:
    name: kube-turbo/continuous-testing-storage
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: undeploy:continuous-testing-storage
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_CT_STORAGE_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/ct-storage/kube-turbo/ | kubectl delete -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:london"
    - "du:stellantis-us"
    - "cluster:ct-storage"

#-------------------------------------------------------------------------------
# cluster: fcaus-ct
#-------------------------------------------------------------------------------

ctkube-kube-turbo:
  environment:
    name: kube-turbo/continuous-testing
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: deploy:continuous-testing
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $FCAUS_CT_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/ctkube/kube-turbo/ | kubectl apply -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:london"
    - "du:stellantis-us"
    - "cluster:ctkube"

undeploy:ctkube-kube-turbo:
  environment:
    name: kube-turbo/continuous-testing
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: undeploy:continuous-testing
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $FCAUS_CT_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/ctkube/kube-turbo/ | kubectl delete -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:london"
    - "du:stellantis-us"
    - "cluster:ctkube"

#-------------------------------------------------------------------------------
# cluster: fcaus-p
#-------------------------------------------------------------------------------

hillsboro-kube-turbo:
  environment:
    name: kube-turbo/hillsboro
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: deploy:hillsboro
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $FCAUS_HILLSBORO_DEPLOYER_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/hillsboro/kube-turbo/ | kubectl apply -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:hillsboro"
    - "du:stellantis-us"

undeploy:hillsboro-kube-turbo:
  environment:
    name: kube-turbo/hillsboro
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: undeploy:hillsboro
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $FCAUS_HILLSBORO_DEPLOYER_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/hillsboro/kube-turbo/ | kubectl delete -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:hillsboro"
    - "du:stellantis-us"

#-------------------------------------------------------------------------------
# cluster: fcaus-p-storage
#-------------------------------------------------------------------------------

hillsboro-storage-kube-turbo:
  environment:
    name: kube-turbo/hillsboro-storage
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: deploy:hillsboro-storage
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_HILLSBORO_STORAGE_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/hillsboro-storage/kube-turbo/ | kubectl apply -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:hillsboro"
    - "du:stellantis-us"

undeploy:hillsboro-storage-kube-turbo:
  environment:
    name: kube-turbo/hillsboro-storage
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: undeploy:hillsboro-storage
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_HILLSBORO_STORAGE_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/hillsboro-storage/kube-turbo/ | kubectl delete -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:hillsboro"
    - "du:stellantis-us"

#-------------------------------------------------------------------------------
# Cluster: fcaus-test
#-------------------------------------------------------------------------------

test-infrastructure-kube-turbo:
  environment:
    name: kube-turbo/test-infrastructure
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: deploy:test-infrastructure
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_TEST_DEPLOYER_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/test/kube-turbo/ | kubectl apply -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:london"
    - "du:stellantis-us"

undeploy:test-infrastructure-kube-turbo:
  environment:
    name: kube-turbo/test-infrastructure
  image: $CI_REGISTRY/fcaus/support/kustom-docker:$KUSTOM_DOCKER_VERSION
  needs: []
  stage: undeploy:test-infrastructure
  script:
    - mkdir -p $(dirname $KUBECONFIG)
    - thycotic get --secret.id $STELLANTIS_TEST_DEPLOYER_KUBECONFIG_SECRET_ID field kubernetes-config config-file >$KUBECONFIG
    - kubectl version --client=true
    - kubectl auth can-i get pods
    - ./build-with-plugins.sh cluster/test/kube-turbo/ | kubectl delete -f - 2>&1 | sed /unchanged/d
  when: manual
  tags:
    - "dc:london"
    - "du:stellantis-us"
