apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    name: registry
spec:
  ports:
    - name: external-http
      port: 8081
      nodePort: 30020
      protocol: TCP
      targetPort: http
  selector:
    name: registry
  type: NodePort